CREATE TABLE IF NOT EXISTS product (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  site_id INTEGER NOT NULL,
  url TEXT NOT NULL UNIQUE,
  FOREIGN KEY (site_id) REFERENCES site (id) ON DELETE CASCADE
);
